// build.js
// Vercel runs this automatically on every deploy (set as Build Command in vercel.json).
// It reads your secret env vars from Vercel Dashboard and writes them into _config.js.
// Your GitHub repo NEVER has real keys — only this build script runs with them on Vercel servers.

const fs = require('fs');

const SUPABASE_URL    = process.env.SUPABASE_URL    || '';
const SUPABASE_ANON   = process.env.SUPABASE_ANON   || '';
const ADMIN_EMAIL     = process.env.ADMIN_EMAIL     || '';
const RAZORPAY_KEY_ID = process.env.RAZORPAY_KEY_ID || '';

if (!SUPABASE_URL || !SUPABASE_ANON) {
  console.error('');
  console.error('❌  ERROR: SUPABASE_URL or SUPABASE_ANON is missing!');
  console.error('    Go to: Vercel Dashboard → Your Project → Settings → Environment Variables');
  console.error('    Add SUPABASE_URL and SUPABASE_ANON then redeploy.');
  console.error('');
  process.exit(1);
}

const output = `// AUTO-GENERATED by build.js during Vercel deployment — do not edit manually
// This file is created fresh on every deploy with values from Vercel Environment Variables
window.__MGR_CFG__ = {
  url:  "${SUPABASE_URL}",
  anon: "${SUPABASE_ANON}",
  adm:  "${ADMIN_EMAIL}",
  rzp:  "${RAZORPAY_KEY_ID}"
};
`;

fs.writeFileSync('_config.js', output);
console.log('✅  build.js: _config.js written successfully with env var values.');
